name: Default

on: 
  push:
    branches:    
      - '*'
      - '!master'

jobs:
  setup-linux:
    name: Setup - Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
      - uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - uses: actions/cache@v1
        id: submodule-cache
        with:
          path: src/shared/node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('src/shared/yarn.lock') }}
      - name: Yarn Install
        if: steps.cache.outputs.cache-hit != 'true' || steps.submodule-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
  test-lint:
    name: Test - Lint
    runs-on: ubuntu-latest
    needs: setup-linux
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
      - uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - uses: actions/cache@v1
        id: submodule-cache
        with:
          path: src/shared/node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('src/shared/yarn.lock') }}
      - name: Lint
        run: yarn lint
  test-typecheck:
    name: Test - Type Check
    runs-on: ubuntu-latest
    needs: setup-linux
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
      - uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - uses: actions/cache@v1
        id: submodule-cache
        with:
          path: src/shared/node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('src/shared/yarn.lock') }}
      - name: Type Check
        run: yarn typescript
  test-jest:
    name: Test - Jest
    runs-on: ubuntu-latest
    needs: setup-linux
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
      - uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - uses: actions/cache@v1
        id: submodule-cache
        with:
          path: src/shared/node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('src/shared/yarn.lock') }}
      - name: Test
        run: yarn coverage
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          AMPLITUDE_KEY: ${{ secrets.AMPLITUDE_KEY }}
          AWS_APPSYNC_URL: ${{ secrets.AWS_APPSYNC_URL }}
          AWS_APPSYNC_REGION: ${{ secrets.AWS_APPSYNC_REGION }}
          AWS_APPSYNC_API_KEY: ${{ secrets.AWS_APPSYNC_API_KEY }}
          CONTENTFUL_SPACE: ${{ secrets.CONTENTFUL_SPACE }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_ACCESS_TOKEN_DRAFTS: ${{ secrets.CONTENTFUL_ACCESS_TOKEN_DRAFTS }}
      - uses: codecov/codecov-action@v1
  deploy-vercel:
    name: Deploy - Vercel
    runs-on: ubuntu-latest
    needs: setup-linux
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
      - uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - uses: actions/cache@v1
        id: submodule-cache
        with:
          path: src/shared/node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('src/shared/yarn.lock') }}
      - uses: amondnet/vercel-action@v19.0.1+2
        id: vercel
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-org-id: ${{ secrets.ORG_ID }}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID }} #Required
          alias-domains: |
            staging.dailytargum.com
            staging-dailytargum.now.sh
  audit:
    name: Auddit - Staging Website
    runs-on: ubuntu-latest
    needs: deploy-vercel
    steps:
      - name: Audit home page
        uses: jakejarvis/lighthouse-action@master
        continue-on-error: true
        with:
          url: https://staging.dailytargum.com/
      - name: Audit news section
        uses: jakejarvis/lighthouse-action@master
        continue-on-error: true
        with:
          url: https://staging.dailytargum.com/section/news
      - name: Audit sports section
        uses: jakejarvis/lighthouse-action@master
        continue-on-error: true
        with:
          url: https://staging.dailytargum.com/section/sports
      - name: Audit opinions section
        uses: jakejarvis/lighthouse-action@master
        continue-on-error: true
        with:
          url: https://staging.dailytargum.com/section/opinions
      - name: Audit inside beat section
        uses: jakejarvis/lighthouse-action@master
        continue-on-error: true
        with:
          url: https://staging.dailytargum.com/section/inside-beat
      - name: Audit dynamic page (privacy policy)
        uses: jakejarvis/lighthouse-action@master
        continue-on-error: true
        with:
          url: https://staging.dailytargum.com/page/privacy-policy
      - name: Audit videos page
        uses: jakejarvis/lighthouse-action@master
        continue-on-error: true
        with:
          url: https://staging.dailytargum.com/videos
      - name: Audit photos page
        uses: jakejarvis/lighthouse-action@master
        continue-on-error: true
        with:
          url: https://staging.dailytargum.com/photos
      - name: Audit HoRU page
        uses: jakejarvis/lighthouse-action@master
        continue-on-error: true
        with:
          url: https://staging.dailytargum.com/section/humans-of-rutgers
      - name: Audit podcast page
        uses: jakejarvis/lighthouse-action@master
        continue-on-error: true
        with:
          url: https://staging.dailytargum.com/podcasts/targum-tea
      - name: Upload results as an artifact
        uses: actions/upload-artifact@master
        continue-on-error: true
        with:
          name: report
          path: './report'
